/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatSession {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'messageCount' : bigint,
}
export interface Message {
  'id' : string,
  'content' : string,
  'role' : string,
  'timestamp' : bigint,
  'sessionId' : string,
}
export interface Tool {
  'id' : string,
  'url' : string,
  'name' : string,
  'description' : string,
  'iconEmoji' : string,
  'category' : string,
}
export interface UserProfile { 'name' : string, 'creditsRemaining' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMessage' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChatSession' : ActorMethod<[string], string>,
  'deleteChatSession' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFlorenceResponse' : ActorMethod<[string], string>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listChatSessions' : ActorMethod<[], Array<ChatSession>>,
  'listTools' : ActorMethod<[], Array<Tool>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];